# golangci-lint v2.3.0 配置檔案
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocyclo
    - goconst
    - revive
    - gocritic
    - importas

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
        disabled: true